services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Apps/WebAPI/Dockerfile
    depends_on:
        - postgres
        # - rabbitmq
    environment:
        - ConnectionString=Host=postgres;Database=postgres;Username=postgres;Password=root;Include Error Detail=true
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - PrivateKey=7QkSdcJ1IFlw1er46k7k0Wwvc3AAYYDm
        # - EventBusConnection=rabbitmq
        # - SubscriptionClientName=scheduler
    ports:
      - "80"
      - "443"
  scheduler:
    image: ${DOCKER_REGISTRY-}scheduler
    build:
      context: .
      dockerfile: Apps/Scheduler/Dockerfile
    depends_on:
        - postgres
        # - rabbitmq
    environment:
        - ConnectionString=Host=postgres;Database=postgres;Username=postgres;Password=root;Include Error Detail=true
        - ASPNETCORE_ENVIRONMENT=Development
        - PrivateKey=7QkSdcJ1IFlw1er46k7k0Wwvc3AAYYDm
      
      # - EventBusConnection=rabbitmq
        # - SubscriptionClientName=scheduler
  apigw:
    image: ${DOCKER_REGISTRY-}apigw
    build:
      context: .
      dockerfile: BuildingBlocks/ApiGateway/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
    - webapi
    ports:
    - "5000:80"
    - "5001:443"
  postgres:
    image: "postgres"
    container_name: postgres-dev
    environment:
        - POSTGRES_PASSWORD=root
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: "dpage/pgadmin4:latest"
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@nonexistent.environment
        - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
        - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  # rabbitmq:
  #   image: "rabbitmq:3-management-alpine"
  #   container_name: rabbitmq
  #   restart: always
  #   ports:
  #   - "5672:5672"
  #   - "15672:15672"
volumes:
  postgres_data:
  pgadmin_data:
  