services:
  webapi:
    environment:
        - ASPNETCORE_Kestrel__Certificates__Default__Password=somepass
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/
  apigw:
    environment:
    - ASPNETCORE_Kestrel__Certificates__Default__Password=somepass
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/
