name: ci

on:
  push:
    branches:
    - master

permissions:
  contents: write
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Apps/WebAPI/Dockerfile
            image: ghcr.io/OpenSoftwareYard/chyve-ct-webapi
            context: .
            service: webapi
          - dockerfile: ./Apps/Scheduler/Dockerfile
            image: ghcr.io/OpenSoftwareYard/chyve-ct-scheduler
            context: .
            service: scheduler
          - dockerfile: ./BuildingBlocks/ApiGateway/Dockerfile
            image: ghcr.io/OpenSoftwareYard/chyve-ct-apigw
            context: .
            service: apigw
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: "${{matrix.image}}:${{ github.sha }}"
          labels: ${{ steps.meta.outputs.labels }}
      - name: Set tags
        id: output
        run: |
          echo "${{ matrix.service }}=${{ github.sha }}" >> $GITHUB_OUTPUT
    outputs:
      webapi: ${{ steps.output.outputs.webapi }}
      scheduler: ${{ steps.output.outputs.scheduler }}
      apigw: ${{ steps.output.outputs.apigw }}
