name: release

on:
  push:
    tags:
    - "*"

permissions:
  contents: write
  packages: write

jobs:
  build-and-push-dotnet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: |
        dotnet build --configuration Release Chyve-ct.sln
        dotnet publish -c Release -r linux-x64 --self-contained true /p:UseAppHost=true Chyve-ct.sln
    - name: Package
      run: |
        tar czf chyve-ct.tar.gz Apps/Scheduler/bin/Release/net9.0/linux-x64/publish Apps/WebAPI/bin/Release/net9.0/linux-x64/publish BuildingBlocks/ApiGateway/bin/Release/net9.0/linux-x64/publish
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: chyve-ct.tar.gz
